version: '3.9'

services:
    stat_ua:
      build: ./covid19
      privileged: true
      container_name: stat_ua
      deploy:
        resources:
          limits:
            cpus: '0.75'
            memory: 196M
          #reservations:
          #  cpus: '0.50'
          #  memory: 128M
      ports:
        - 8000:8000